![title](pictures/grid.png)

In [110]:
import numpy as np
def next_s(s,a):
    
    # Special states and rewards
    # A
    if s == (0,1):
        return (4,1), 10
    # B
    if s == (0,3):
        return (2,3), 5
    
    # Corner cases
    sy, sx = s
    r = -1
    # North
    if sy == 0 and a==0:
        return s,r
    # East
    if sx == 4 and a==1:
        return s,r
    # South
    if sy == 4 and a==2:
        return s,r
    # West
    if sx == 0 and a==3:
        return s,r
    
    # Regular cases
    r = 0
    # move agent
    sy += ((a+1)%2)*(a-1)
    sx += ((a)%2)*(2-a)
    new_s = (int(sy),int(sx))
    return new_s, r

# Policy improvement

![title](pictures/policyeval.png)

In [111]:
# 1. Initialization

## Actions 
A = [0,1,2,3] # north, east, south, west


## Initialize random policy

policy = np.zeros((5,5))
for i in range(5):
    for j in range(5):
        policy[i][j] = np.random.choice(A)

## Initialize random V values
V = np.random.randn(5,5)




policy_stable = False
while not policy_stable:
    # 2. Policy Evaluation

    delta = 1.
    epsilon = 0.01
    gamma = 0.9

    while delta > epsilon:
        delta = 0
        for i in range(5):
            for j in range(5):
                s = (i,j) # state
                v = V[s] # state value
                s_next, r = next_s(s,policy[s]) # next state and reward
                #print(s_next, r)

                V[s] = r + gamma*V[s_next] # V update
                #print(v)
                #print(V[s])
                delta = np.max([delta, np.abs(v- V[s])])

    # 3. Policy Improvement

    policy_stable = True
    for i in range(5):
        for j in range(5):
            s = (i,j)
            old_action = policy[s]
            policy[s] = np.argmax([next_s(s,action)[1] + gamma*V[next_s(s,action)[0]] for action in range(4)])
            if old_action != policy[s]:
                policy_stable = False

            
            




![title](pictures/Gridworld.png)

## My results :)

### Optimal policy

In [112]:
print(policy)

[[1. 0. 3. 0. 3.]
 [1. 0. 0. 3. 3.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


### Optimal v with gamma=0.9:

In [113]:
print(np.round(V,1))

[[22.  24.4 22.  19.4 17.5]
 [19.8 22.  19.8 17.8 16. ]
 [17.8 19.8 17.8 16.  14.4]
 [16.  17.8 16.  14.4 13. ]
 [14.4 16.  14.4 13.  11.7]]


# Conclusion

### If we have a completely defined Markov Decision Process, we can easily obtain the optimal policy iteratively
